### ISSUE TITLE
The prescription PDF only contains the edoc ID when using a project-level PDF template

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/send_rx#102]
The prescription PDF returns a document which only contains a number rather than the template with the proper information filled in; the number in the PDF appears to be the edoc_id of the PDF template defined at the project level. During a prior investigation I suspected a change may need to be made around here: https://github.com/ctsit/send_rx/blob/baa8f361d2827a9341c1a0ee70d565beb2d5b46d/includes/RxSender.php#L296-L302

Defining an overriding template in a record in the Sites project circumvents this, but it is a tedious manual process.

**Comment by pbchase** [comment]
addressed by PR #103
