### ISSUE TITLE
Add a link to the subject's record_home page in the pharmacist's email alert

### ISSUE THREAD

**Issue by pbchase** [ctsit/send_rx#59]
The email delivered by send_rx only provides a link to the pdf of the prescription.  Should there be ancillary information on a REDCap form that is useful to the pharmacist, accessing those forms is tedious. send_rx should provide an additional link that makes this access easier. That link should route the pharmacist to subject's record home page. The forms visible to the pharmacist via this link is configured solely by REDCap's authorization system. i.e., authorization is not in the scope of this change.  

The text surrounding this link should be something like this:

> There is a new prescription ready to be filled for a study participant on the WARRIOR project. The file is accessible at: https://redcap.example.org/redcap_v8.0.3/DataEntry/file_download.php?pid=13&record=12... 
> 
> Additional data about this research participant is accessible at https://redcap.example.org/redcap_v8.0.3/DataEntry/record_home.php?pid=13&id=1-2&arm=1

**Comment by tbembersimeao** [comment]
@pbchase fortunately this feature already exists! There is a piping option for that - `[patient_url]`.

**Comment by pbchase** [comment]
@tbembersimeao, thank you so much. It's almost like we had foresight. :-)
