### ISSUE TITLE
send_rx crashes when writing generating pdf file in redcap version 8.5.0

### ISSUE THREAD

**Issue by rajputd** [ctsit/send_rx#75]
Send_rx was working fine before I upgraded to REDCap version 8.5.0. After I upgraded, I was going through the normal workflow of creating a new patient and filling out the associated info, demographics, and prescription forms. When I selected "save and go to next form", the "Review & Send Rx" page crashed with a php Fatal error:

![image](https://user-images.githubusercontent.com/16458008/41666625-eb54ec92-7478-11e8-96e6-6cc7cea6635c.png)

After some experimenting the issues seems to be in lines 168-170 in send_rx_functions.php. REDCap seems to crash when you use the Mpdf composer dependency. I had a similar issue with redcap_mirth_connect_client when upgrading to REDCap version 8.5.0. Please verify if this is an issue for you as well.

**Comment by marlycormar** [comment]
@rajputd I can confirm I am getting the same error. I am unable to test PR #63 until this issue is resolved.

**Comment by marlycormar** [comment]
@rajputd per our meeting today, I made the corresponding changes to `send_rx_functions.php` (PR #77). This should fix this issue. Could you review it?

**Comment by rajputd** [comment]
Absolutely. I'll check it out on Friday.
